Repository kubevirt/must-gather, pull requests merged in 2019-10, with the labels that each got.

#57 Limit node-gather pod scheduling time
  Dockerfile
  collection-scripts/gather_nodes
Labels: dco-signoff: yes, size/M

#39 Added a bugzilla attach python script
  scripts/bugzilla_attach.py
Labels: dco-signoff: yes, size/L

#58 Added support for multiple images and image stream
  scripts/bugzilla_attach.py
Labels: dco-signoff: yes, size/S
