Repository kubevirt/must-gather, pull requests merged in 2019-07, with the labels that each got.

#13 Fixing incorrect path
  gather_cnv_nodes
Labels: size/XS

#14 Fix for gathering duplicated network pod manifests
  gather_cnv
  gather_cnv_network
Labels: size/S

#15 Use node-gather image from quay
  node-gather/node-gather-ds.yaml
Labels: size/XS

#7 gather logs from v2v conversion pods
  gather_cnv
  gather_cnv_v2v
Labels: size/S

#18 Fix permissions on gather_cnv_v2v
  gather_cnv_v2v
Labels: size/XS

#17 Add automation
  .travis.yml
  Dockerfile
  Makefile
  build/release-manifests.sh
  node-gather/node-gather-ds.yaml.in
Labels: size/M

#16 Communitize must-gather
  Dockerfile
  README.md
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_nodes
  collection-scripts/gather_ssp
  collection-scripts/gather_v2v
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
Labels: size/M

#19 Gather NodeNetworkState
  collection-scripts/gather
Labels: size/XS

#20 Allow makefile to modify image name for node-gather
  Makefile
  build/release-manifests.sh
  node-gather/node-gather-ds.yaml.in
Labels: size/XS

#21 bridge-utils not available on rhel8
  collection-scripts/gather_nodes
  node-gather/Dockerfile
Labels: size/XS
