Repository kubevirt/must-gather, pull requests merged in 2021-11, with the labels that each got.

#99 [Release 4.8] Add targeted gathering to collect VM information (#96 and #97)
  README.md
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_hco
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm

#100 [Release 4.9] Add targeted gathering to collect VM information (#96 and #97)
  README.md
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_hco
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm

#103 Add two more option to gather VM information
  README.md
  collection-scripts/gather_vms_details
Labels: release-note, size/L, dco-signoff: yes, approved, lgtm

#104 Added a log file as part of must-gather output
  Dockerfile
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_hco
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_virtualmachines
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
  collection-scripts/logs.sh
  collection-scripts/version
Labels: size/M, release-note, dco-signoff: yes, approved, lgtm

#105 Tag tests
  tests/validate_must_gather_test.go
Labels: size/S, release-note, dco-signoff: yes, approved, lgtm

#106 Gather VM CR by default
  automation/create_workloads.sh
  collection-scripts/gather
  collection-scripts/gather_crs
  collection-scripts/gather_virtualmachines
  tests/utils_test.go
  tests/validate_must_gather_test.go
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm

#107 Collect basic VM info also from the gather_vms_details script
  collection-scripts/gather_crs
  collection-scripts/gather_vms_details
Labels: size/XS, release-note, dco-signoff: yes, approved, lgtm

#108 [Release 4.9] Adopt the bug fixes and logs from the main branch
  automation/create_workloads.sh
  automation/ns.yaml
  automation/vm.yaml
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_hco
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_v2v
  collection-scripts/gather_virtualmachines
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
  collection-scripts/logs.sh
  collection-scripts/version
  tests/utils_test.go
  tests/validate_must_gather_test.go
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm

#109 [Release 4.8] Adopt the bug fixes and logs from the main branch
  automation/create_workloads.sh
  automation/ns.yaml
  automation/vm.yaml
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_hco
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_v2v
  collection-scripts/gather_virtualmachines
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
  collection-scripts/logs.sh
  collection-scripts/version
  tests/utils_test.go
  tests/validate_must_gather_test.go
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm
