Repository kubevirt/must-gather, pull requests merged in 2021-08, with the labels that each got.

#84 Improve automation
  automation/create_workloads.sh
  automation/deploy_hco.sh
  automation/vm.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#85 Allow overriding the CNV namespace for community deploymet
  Dockerfile
  collection-scripts/gather
  collection-scripts/gather_hco
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#86 Write some test to validate the gathered information
  tests/.gitignore
  tests/go.mod
  tests/main_test.go
  tests/utils_test.go
  tests/validate_must_gather_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, approved, lgtm

#88 Update reviewer list
  OWNERS_ALIASES
Labels: size/XS, release-note-none, dco-signoff: yes, approved

#87 Add the tests/go.sum file
  tests/go.mod
  tests/go.sum
Labels: release-note-none, size/L, dco-signoff: yes, approved, lgtm

#90 Add Junit reporter to the CI tests
  tests/main_test.go
  tests/utils_test.go
Labels: size/M, release-note-none, dco-signoff: yes, approved, lgtm

#91 Gather SELinux logs from nodes
  collection-scripts/gather_nodes
  tests/validate_must_gather_test.go
Labels: approved, lgtm
