Repository kubevirt/must-gather, pull requests merged in 2022-01, with the labels that each got.

#112 Improve the gather_virtualmachines script
  Dockerfile
  automation/create_workloads.sh
  collection-scripts/gather_virtualmachines
  tests/validate_must_gather_test.go
Labels: size/M, release-note, dco-signoff: yes, approved, lgtm

#113 add shellcheck sanity github action
  .github/workflows/pr-sanity.yaml
  Makefile
  collection-scripts/gather
  collection-scripts/gather_apiservices
  collection-scripts/gather_cdi
  collection-scripts/gather_crds
  collection-scripts/gather_crs
  collection-scripts/gather_images
  collection-scripts/gather_nodes
  collection-scripts/gather_ns
  collection-scripts/gather_ssp
  collection-scripts/gather_virtualmachines
  collection-scripts/gather_vms_details
  collection-scripts/gather_vms_namespaces
  collection-scripts/gather_webhooks
  collection-scripts/logs.sh
  collection-scripts/version
Labels: release-note-none, size/L, dco-signoff: yes, approved, lgtm

#114 [release-4.9] Improve the gather_virtualmachines script
  Dockerfile
  automation/create_workloads.sh
  collection-scripts/gather_virtualmachines
  tests/validate_must_gather_test.go
Labels: size/M, release-note, dco-signoff: yes, approved, lgtm

#120 Fix the validate nodes logs functional test
  tests/validate_must_gather_test.go
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#116 nftables: Fix collecting nftables from nodes
  collection-scripts/gather_nodes
  tests/validate_must_gather_test.go
Labels: size/XS, release-note-none, dco-signoff: yes, approved, lgtm

#115 network: Fix rule tables collecting
  collection-scripts/gather_vms_details
  tests/validate_must_gather_test.go
Labels: size/M, release-note-none, dco-signoff: yes, approved, lgtm

#119 sriov: Update sriov namespace
  collection-scripts/gather_ns
Labels: size/XS, release-note-none, dco-signoff: yes, approved, lgtm

#122 [Release 4.9] Fix the gather_vms_details, by exporting some env vars
  collection-scripts/gather_vms_details
Labels: size/XS, release-note, dco-signoff: yes, approved, lgtm
