Repository kubevirt/must-gather, pull requests merged in 2022-04, with the labels that each got.

#136 Fix BZ 2058925: failed to get detailed for VMs with long names
  collection-scripts/gather_vms_details
Labels: size/S, release-note, dco-signoff: yes, approved, lgtm

#135 Update the HCO version in the e2e tests
  automation/deploy_hco.sh
  tests/validate_must_gather_test.go
Labels: size/XL, release-note-none, dco-signoff: yes, approved, lgtm

#140 Update the owner list
  OWNERS_ALIASES
Labels: size/XS, release-note-none, dco-signoff: yes, approved, lgtm

#144 Add test commands to Makefile
  Makefile
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#145 [release-4.10] Add test commands to Makefile
  Makefile
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#143 Add script to delete tests workloads
  automation/delete_workloads.sh
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm
