Repository kubevirt/must-gather, pull requests merged in 2023-11, with the labels that each got.

#199 [Release 4.11] bump golang to 1.17
  tests/go.mod
  tests/vendor/github.com/Azure/go-autorest/autorest/adal/go.mod
  tests/vendor/github.com/Azure/go-autorest/autorest/adal/go.sum
  tests/vendor/github.com/Azure/go-autorest/autorest/date/go.mod
  tests/vendor/github.com/Azure/go-autorest/autorest/date/go.sum
  tests/vendor/github.com/Azure/go-autorest/autorest/go.mod
  tests/vendor/github.com/Azure/go-autorest/autorest/go.sum
  tests/vendor/github.com/Azure/go-autorest/logger/go.mod
  tests/vendor/github.com/Azure/go-autorest/logger/go.sum
  tests/vendor/github.com/Azure/go-autorest/tracing/go.mod
  tests/vendor/github.com/Azure/go-autorest/tracing/go.sum
  tests/vendor/github.com/go-logr/logr/go.mod
  tests/vendor/github.com/google/gofuzz/go.mod
  tests/vendor/github.com/json-iterator/go/go.mod
  tests/vendor/github.com/json-iterator/go/go.sum
  tests/vendor/github.com/onsi/ginkgo/v2/go.mod
  tests/vendor/github.com/onsi/ginkgo/v2/go.sum
  tests/vendor/github.com/onsi/gomega/go.mod
  tests/vendor/github.com/onsi/gomega/go.sum
  tests/vendor/github.com/spf13/pflag/go.mod
  tests/vendor/github.com/spf13/pflag/go.sum
  tests/vendor/golang.org/x/oauth2/go.mod
  tests/vendor/golang.org/x/oauth2/go.sum
  tests/vendor/golang.org/x/term/go.mod
  tests/vendor/golang.org/x/term/go.sum
  tests/vendor/google.golang.org/appengine/go.mod
  tests/vendor/google.golang.org/appengine/go.sum
  tests/vendor/gopkg.in/yaml.v2/go.mod
  tests/vendor/gopkg.in/yaml.v3/go.mod
  tests/vendor/k8s.io/klog/v2/go.mod
  tests/vendor/k8s.io/klog/v2/go.sum
  tests/vendor/modules.txt
  tests/vendor/sigs.k8s.io/yaml/go.mod
  tests/vendor/sigs.k8s.io/yaml/go.sum
Labels: size/XL, release-note, dco-signoff: yes, approved, lgtm

#200 Add sleep to the create_workloads.sh
  automation/create_workloads.sh
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#202 Add sleeps to automation/create_workloads.sh
  automation/create_workloads.sh
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#203 [release-412] Add sleeps to automation/create_workloads.sh
  automation/create_workloads.sh
Labels: size/S, release-note-none, dco-signoff: yes, approved, lgtm

#191 Collect running VMs count
  collection-scripts/gather
  collection-scripts/gather_virtualization
  tests/validate_must_gather_test.go
Labels: size/M, release-note, dco-signoff: yes, approved, lgtm
